---
networks:
  wordpress_net:

volumes:
  db_data:
  wp_data:

services:
  # :: Primary stack database
  wordpress-db:
    image: mariadb:latest
    restart: always
    networks:
      - wordpress_net

    volumes:
      - db_data:/var/lib/mysql

    expose:
      - 3306
      - 33060

    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  #  :: Core webserver
  wordpress-core:
    image: wordpress:latest
    restart: always
    networks:
      - wordpress_net

    volumes:
      - wp_data:/var/www/html

    expose:
      - 80

    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

  # :: Load balancing
  core-loadbalancing:
    image: nginx:1.22.1
    restart: always
    networks:
      - wordpress_net

    ports:
      - 80:80

    volumes:
      - ./.nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - wordpress-core
